---
- name: Monitor Zero Trust Policy
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - "https://unmystic-jonnie-nonterminatively.ngrok-free.dev/api/l252IftczLmVwO6DF0f66Ugy0IhaZ23c1jh4ZQPY/lights/1"
        delay: 5
        verify_ssl: false
        # We must add the ngrok bypass header here too so EDA can see the JSON
        headers:
          ngrok-skip-browser-warning: "true"

  rules:
    - name: Detect Configuration Drift
      # This triggers if the light is NOT the specific Green XY coordinates
      condition: event.url_check.status == "up"
      action:
        run_job_template:
          name: "Policy-Enforcement-Green"
          organization: "Default"
